### ISSUE TITLE
Retrieve configuration data from Database instead of settings.py

### ISSUE THREAD

**Issue by mauroka** [snok/django-auth-adfs#102]
Hello.
Is it possible to retrieve configuration data from Database instead of settings.py?
So this can work with multiple tenants in the same project?

Thank you.
Regards.

**Comment by jobec** [comment]
Due to the overhead involved in getting the configuration from ADFS, It's kept in memory.

Storing multiple such configs should be possible, but it all depends on how you implemented multiple tenants in your project. I guess you also have split the user, groups, permissions databases etc? This could get complex very fast...

**Comment by JonasKs** [comment]
Hi @mauroka , would you like to submit a PR for this? 

This is not something I will look into implementing personally.

**Comment by mauroka** [comment]
Hello @JonasKs.
Not at this moment.

**Comment by JonasKs** [comment]
As jobec mentioned, this is a quite big implementation, and I think it's a bit out of scope as there are probably smarter ways of achieving this. (Such as multipod with a dedicated settings/db-settings etc.)

For that reason I'll close this for now. We can re-open it if someone wants to spec the design a bit more.
