### ISSUE TITLE
How to set redirect uri

### ISSUE THREAD

**Issue by MichaelCordero98** [snok/django-auth-adfs#224]
How do I configure the redirect uri so that it points to our website - "https://ourwebsite.com/oauth2/callback" instead of "http://localhost:8000/oauth2/callback"? I see that the source code has deprecated the "REDIR_URI" field, so I'm not sure how I would go about doing so. Thanks!

**Comment by MaKyOtOx** [comment]
up ?

**Comment by QuentinAndre11** [comment]
From my understanding, redirect_uri directly depends on your host. So, in your browser, instead of using http://localhost:8000/, use https://ourwebsite.com/. You might need to update your DNS and ALLOWED_HOSTS.
Note that it will still redirect to http instead of https (see FAQ).
Another solution if you're working with localhost (for development) is to add http://localhost:8000/oauth2/callback to the ADFS redirect URI list on your ADFS manager as shown in documentation.
