### ISSUE TITLE
exempt url not working

### ISSUE THREAD

**Issue by Mergpijp** [snok/django-auth-adfs#239]
I followed the guide and tried exempting the rest framework from authentication:

```
    'LOGIN_EXEMPT_URLS': [
        'api/',  # Assuming you API is available at /api
    ],
```
I tried variations but it keeps asking to login when accessing the api. What is causing this?

**Comment by JonasKs** [comment]
These are regex-based exempt URLs, and only allow you to not be redirected to a login page. It don't actually disable authentication on your view.

**Comment by JonasKs** [comment]
Deleted my previous reply since it was so badly formulated.. I'm sorry, wrote it in a rush. 

The `LOGIN_EXEMPT_URLS` disable auth on your _normal_ views, but not views handled by DRF themself. So if you have added authentication to the `REST_FRAMEWORK` setting such as `DEFAULT_AUTHENTICATION_CLASSES` you'll still be prompted to authenticate. 

Remember `LOGIN_EXEMPT_URLS` items are interpreted as regex.

Read more here: https://django-auth-adfs.readthedocs.io/en/latest/rest_framework.html

**Comment by Mergpijp** [comment]
Yes solved this by using basic authentication in the rest framework and removing the login required decorator in urls.
